                                       

source = bind.conf                 #Contains Keybindinf
source = animation.conf            #Contains Hyprland Animations
source = looknfeel.conf            #Contains Aestetics of Window Manager
source = permissions.conf          #Contains Optional Permissions Module
source = startup.conf              #Contains Apps That Startup at boot
source = env.conf                  #Contains The Enviroment Variables
source = input.conf                #Contains The Input Devices
source = colors.conf


################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=HDMI-A-1,1920x1080@60,0x0,1
monitor=eDP-1,2560x1600@60,1920x0,1.25

workspace=1,monitor:HDMI-A-1
workspace=2,monitor:HDMI-A-1
workspace=3,monitor:HDMI-A-1
workspace=4,monitor:HDMI-A-1
workspace=5,monitor:HDMI-A-1
workspace=6,monitor:eDP-1


##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules


###############
### PLUGINS ###
###############


plugin {
  split-monitor-workspaces {
    count = 5                   # 5 workspaces per monitor
    keep_focused = 0
    enable_persistent_workspaces = 1
  }
}





decoration {
    rounding = 12
    active_opacity = 0.92
    inactive_opacity = 0.85
    fullscreen_opacity = 1.0
}

exec-once = hyprctl preloadmodule libHyprBlur.so
